.TH PROCTEMPVIEW 1 "July 2013" Linux "User Manuals"
.SH NAME
proctempview \- graphically view processor temperature in a console
.SH SYNOPSIS
.B proctempview
.SH DESCRIPTION
Measure processor temperatures via sensors(1) and graphically display using ncurses(3).
.SH OPTIONS
.IP none
.SH FILES
.I ~/.config/proctemp/proctempviewrc
.RS
User configuration file.
.SH AUTHOR
Jeff Perry <jeffsp@gmail.com>
.SH "SEE ALSO"
.BR proctempalert(1)
