.TH THERMALERT 1 "July 2013" Linux "User Manuals"
.SH NAME
thermalert \- alert the user when processor temperature becomes high
.SH SYNOPSIS
.B thermalert [-i '...'|--high_cmd='...'] [-c '...'|--critical_cmd='...'] [-d#|--debug=#] [-h|--help] [-g|--gpus]
.SH DESCRIPTION
Measure the cpu temperatures and run commands if the temperatures are high.
.P
You can run this command from your crontab to alert you via email when your processor gets too hot.
.SH OPTIONS
.IP "-i ' '|--high_cmd='cmd ...'"
Run this command if the cpu temperature is high.
.IP "-c ' '|--critical_cmd='cmd ...'"
Run this command if the cpu temperature is critical.
.IP "-d#|--debug=#"
Use for debugging.  To force the program to behave as though a processor temperature is high, set # equal to
1.  Set # equal to 2 to force it to behave as though a processor temperature is critical.

This can be useful when you
are configuring thermalert to run in your crontab.
.IP "-h|--help"
Get help
.IP "-b#|--bus=#"
Specify the bus id to check:

	0=I2C, 1=ISA, 2=PCI, 3=SPI, 4=VIRTUAL, 5=ACPI, 6=HID

.SH RETURN
The program returns the following error codes to the shell.
.IP 0
OK
.IP 1
Temperature is hot
.IP 2
Temperature is critically hot
.SH EXAMPLES
Here are some example crontab entries:
.P
.nf
	# every tens minutes, check if temperature is high
.nf
	*/10 * * * * /usr/local/bin/thermalert --high_cmd='sensors | mail -s "`hostname` is HIGH" username@email.com' &> /dev/null

.P
.nf
	# every two minutes, check if CPU temperature is critical
.nf
	*/2 * * * *	/usr/local/bin/thermalert --bus_id=1 --critical_cmd='sensors | mail -s "`hostname` is CPU CRITICAL" username@email.com' &> /dev/null
.P
.nf
	# every two minutes, check if GPU temperature is critical
.nf
	*/2 * * * *	/usr/local/bin/thermalert --bus_id=2 --critical_cmd='sensors | mail -s "`hostname` is GPU CRITICAL" username@email.com' &> /dev/null

.SH AUTHOR
Jeff Perry <jeffsp@gmail.com>
.SH "SEE ALSO"
.BR therm(1)
.BR crontab(1)
.BR crontab(5)
